/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookhub;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author das_p
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    void showDate()
    {
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");
        date.setText(s.format(d));
    }
    void showTime()
    {
       new Timer(0,new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e) {
             Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
        time.setText(s.format(d));  
           }
       }
       ).start();
    }
    int mouseX;
    int mouseY;
     Connection conn=null;
    OraclePreparedStatement pst=null;
    OracleResultSet rs=null;
    public HomePage() {
        initComponents();
        this.setLocationRelativeTo(null);
        conn=JavaConnectDb.ConnecrDb();
        showDate();
        showTime();
    }
    /* public void add()
    {
        try{
            String sql="select * from book";
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            rs=(OracleResultSet) pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }*/
private void refresh1()
{
    jtext1.setText(null);
    jtext2.setText(null);
    jComboBox2.setSelectedIndex(0);
    jtext3.setText(null);
    jtext4.setText(null);
    jtext5.setText(null);
    jtext6.setText(null);
    jtext7.setText(null);
}
private void refresh2()
{
    jtext8.setText(null);
    jtext9.setText(null);
    jComboBox1.setSelectedIndex(0);
    jtext10.setText(null);
    jtext11.setText(null);
    jtext12.setText(null);
    jtext13.setText(null);
    jtext14.setText(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menupanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        side_menu = new javax.swing.JPanel();
        rSButton2 = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();
        rSButton5 = new rojeru_san.RSButton();
        rSButton6 = new rojeru_san.RSButton();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        rSButton7 = new rojeru_san.RSButton();
        jLabel34 = new javax.swing.JLabel();
        rSButton9 = new rojeru_san.RSButton();
        rSButton4 = new rojeru_san.RSButton();
        rSButton10 = new rojeru_san.RSButton();
        home = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        addpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtext1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtext2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtext6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtext3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtext4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtext5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        add_button = new rojeru_san.RSButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jtext7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        rSButton11 = new rojeru_san.RSButton();
        deletepanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtext8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtext9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtext10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtext11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtext12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtext13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rSButton1 = new rojeru_san.RSButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jtext14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        searchpanel = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        updatepanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jtext15 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtext16 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtext17 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jtext18 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jtext19 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtext20 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        rSButton8 = new rojeru_san.RSButton();
        jtext21 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        viewpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menupanel.setBackground(new java.awt.Color(204, 204, 204));
        menupanel.setToolTipText("");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sitka Small", 1, 48)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Welcome to Homepage");
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel10MouseDragged(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menupanelLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menupanelLayout.createSequentialGroup()
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(menupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 70));

        side_menu.setBackground(new java.awt.Color(153, 153, 153));
        side_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButton2.setBackground(new java.awt.Color(153, 153, 153));
        rSButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Project_image/grey_add.png"))); // NOI18N
        rSButton2.setText("ADD");
        rSButton2.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton2.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButton2.setIconTextGap(25);
        rSButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButton2MouseClicked(evt);
            }
        });
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });
        side_menu.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 290, 60));

        rSButton3.setBackground(new java.awt.Color(153, 153, 153));
        rSButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Project_image/grey_home.png"))); // NOI18N
        rSButton3.setText("HOME");
        rSButton3.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton3.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButton3.setIconTextGap(25);
        rSButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton3ActionPerformed(evt);
            }
        });
        side_menu.add(rSButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 290, 60));

        rSButton5.setBackground(new java.awt.Color(153, 153, 153));
        rSButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Project_image/delete_grey.png"))); // NOI18N
        rSButton5.setText("DELETE");
        rSButton5.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton5.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButton5.setIconTextGap(25);
        rSButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton5ActionPerformed(evt);
            }
        });
        side_menu.add(rSButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 290, 60));

        rSButton6.setBackground(new java.awt.Color(153, 153, 153));
        rSButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Project_image/icons8-update-left-rotation-48.png"))); // NOI18N
        rSButton6.setText("UPDATE");
        rSButton6.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton6.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButton6.setIconTextGap(25);
        rSButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton6ActionPerformed(evt);
            }
        });
        side_menu.add(rSButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 290, 60));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("TIME");
        side_menu.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 220, 40));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("DATE");
        side_menu.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 220, 40));

        rSButton7.setBackground(new java.awt.Color(153, 153, 153));
        rSButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Project_image/search_grey.png"))); // NOI18N
        rSButton7.setText("SEARCH");
        rSButton7.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton7.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButton7.setIconTextGap(25);
        rSButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton7ActionPerformed(evt);
            }
        });
        side_menu.add(rSButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 290, 60));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-open-book-100.png"))); // NOI18N
        side_menu.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, -1));

        rSButton9.setBackground(new java.awt.Color(153, 153, 153));
        rSButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Project_image/search_grey.png"))); // NOI18N
        rSButton9.setText("SEARCH");
        rSButton9.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton9.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButton9.setIconTextGap(25);
        rSButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton9ActionPerformed(evt);
            }
        });
        side_menu.add(rSButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 290, 60));

        rSButton4.setBackground(new java.awt.Color(153, 153, 153));
        rSButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        rSButton4.setText("VIEW USERS");
        rSButton4.setAutoscrolls(true);
        rSButton4.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButton4.setIconTextGap(25);
        rSButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton4ActionPerformed(evt);
            }
        });
        side_menu.add(rSButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 290, 60));

        rSButton10.setBackground(new java.awt.Color(153, 153, 153));
        rSButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        rSButton10.setText("MAIN PAGE");
        rSButton10.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButton10.setIconTextGap(25);
        rSButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton10ActionPerformed(evt);
            }
        });
        side_menu.add(rSButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 290, 60));

        getContentPane().add(side_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 750));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        home.setLayout(new java.awt.CardLayout());

        homepanel.setBackground(new java.awt.Color(255, 255, 255));
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Orator Std", 1, 70)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("BOOK-HUB");
        homepanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 102, 51));
        jLabel30.setText("Developed By");
        homepanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 650, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 102, 51));
        jLabel31.setText("Prasenjit Kumar Das");
        homepanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 680, -1, -1));

        jLabel32.setFont(new java.awt.Font("SimSun-ExtB", 1, 30)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 51));
        jLabel32.setText("<html>Knowledge is free here<br>just bring your own container.</html>");
        homepanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 520, 90));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cartoon-boy-carrying-books-vector-1633787.jpg"))); // NOI18N
        jLabel33.setText("jLabel33");
        homepanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 1020));

        home.add(homepanel, "card2");

        addpanel.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("Book ID");

        jtext1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("Book Title");

        jtext2.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setText("Category");

        jtext6.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setText("Author Name");

        jtext3.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 153));
        jLabel6.setText("Publication");

        jtext4.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("Edition");

        jtext5.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jtext5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 153));
        jLabel8.setText("No. of Pages");

        add_button.setText("ADD");
        add_button.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Com", "M.Com", "B.Sc", "BCA", "MCA", "MBA", "Engineering", "Comic", "Historical", "Novels", " " }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 153));
        jLabel20.setText("Price");

        jtext7.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Image");

        image.setBackground(new java.awt.Color(51, 51, 255));
        image.setForeground(new java.awt.Color(51, 0, 255));
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rSButton11.setText("ATTACH");
        rSButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addpanelLayout = new javax.swing.GroupLayout(addpanel);
        addpanel.setLayout(addpanelLayout);
        addpanelLayout.setHorizontalGroup(
            addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpanelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpanelLayout.createSequentialGroup()
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(rSButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(305, Short.MAX_VALUE))
                    .addGroup(addpanelLayout.createSequentialGroup()
                        .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtext2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext7, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))))
        );
        addpanelLayout.setVerticalGroup(
            addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpanelLayout.createSequentialGroup()
                        .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addpanelLayout.createSequentialGroup()
                                .addComponent(jtext1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jtext2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jtext3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addComponent(jtext4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jtext5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jtext6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addpanelLayout.createSequentialGroup()
                        .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addpanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5)
                                .addGap(60, 60, 60))
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jtext7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(addpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpanelLayout.createSequentialGroup()
                        .addComponent(rSButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addpanelLayout.createSequentialGroup()
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        home.add(addpanel, "card3");

        deletepanel.setBackground(new java.awt.Color(255, 204, 102));

        jLabel11.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 153));
        jLabel11.setText("Book ID");

        jtext8.setEditable(false);
        jtext8.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 153));
        jLabel12.setText("Book Title");

        jtext9.setEditable(false);
        jtext9.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 153));
        jLabel13.setText("Category");

        jtext10.setEditable(false);
        jtext10.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 153));
        jLabel14.setText("Author Name");

        jtext11.setEditable(false);
        jtext11.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 153));
        jLabel16.setText("Publication");

        jtext12.setEditable(false);
        jtext12.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 153));
        jLabel17.setText("Edition");

        jtext13.setEditable(false);
        jtext13.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jtext13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext13ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 153));
        jLabel18.setText("No. of Pages");

        rSButton1.setText("DELETE");
        rSButton1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });

        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable2);

        jtext14.setEditable(false);
        jtext14.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jtext14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext14ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 153));
        jLabel19.setText("Price");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Com", "M.Com", "B.Sc", "BCA", "MCA", "MBA", "Engineering", "Comic", "Historical", "Novels", " " }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout deletepanelLayout = new javax.swing.GroupLayout(deletepanel);
        deletepanel.setLayout(deletepanelLayout);
        deletepanelLayout.setHorizontalGroup(
            deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletepanelLayout.createSequentialGroup()
                .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletepanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deletepanelLayout.createSequentialGroup()
                                .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jtext11, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jtext13, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jtext9)
                                .addComponent(jtext8)
                                .addComponent(jtext14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtext12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(deletepanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        deletepanelLayout.setVerticalGroup(
            deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(deletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deletepanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(9, 9, 9)
                        .addComponent(jtext9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(jtext10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        home.add(deletepanel, "card4");

        searchpanel.setBackground(new java.awt.Color(204, 255, 255));

        jComboBox3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "book_id", "book_title", "author_name", "publication" }));
        jComboBox3.setOpaque(false);

        jTextField1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTable3 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jTable3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        javax.swing.GroupLayout searchpanelLayout = new javax.swing.GroupLayout(searchpanel);
        searchpanel.setLayout(searchpanelLayout);
        searchpanelLayout.setHorizontalGroup(
            searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchpanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        searchpanelLayout.setVerticalGroup(
            searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchpanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(searchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        home.add(searchpanel, "card5");

        updatepanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel21.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 153));
        jLabel21.setText("Book ID");

        jtext15.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel22.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 153));
        jLabel22.setText("Book Title");

        jtext16.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 153));
        jLabel23.setText("Category");

        jtext17.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 153));
        jLabel24.setText("Author Name");

        jtext18.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel25.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 153));
        jLabel25.setText("Publication");

        jtext19.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel26.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 153));
        jLabel26.setText("Edition");

        jtext20.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jtext20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext20ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 0, 153));
        jLabel27.setText("No. of Pages");

        rSButton8.setText("UPDATE");
        rSButton8.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton8ActionPerformed(evt);
            }
        });

        jtext21.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jtext21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jtext21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext21ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 0, 153));
        jLabel28.setText("Price");

        jComboBox4.setEditable(true);
        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Com", "M.Com", "B.Sc", "BCA", "MCA", "MBA", "Engineering", "Comic", "Historical", "Novels", " " }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jTable4 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jTable4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable4);

        javax.swing.GroupLayout updatepanelLayout = new javax.swing.GroupLayout(updatepanel);
        updatepanel.setLayout(updatepanelLayout);
        updatepanelLayout.setHorizontalGroup(
            updatepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(updatepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addGroup(updatepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtext21, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updatepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel26)
                                .addComponent(jtext18)
                                .addComponent(jtext17)
                                .addComponent(jLabel22)
                                .addComponent(jtext15)
                                .addComponent(jtext16)
                                .addComponent(jLabel21)
                                .addComponent(jLabel23)
                                .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25)
                                .addComponent(jtext19)
                                .addComponent(jLabel27)
                                .addComponent(jtext20, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(rSButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        updatepanelLayout.setVerticalGroup(
            updatepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(updatepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addGroup(updatepanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(2, 2, 2)
                        .addComponent(jtext17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(rSButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );

        home.add(updatepanel, "card6");

        jTable1= new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout viewpanelLayout = new javax.swing.GroupLayout(viewpanel);
        viewpanel.setLayout(viewpanelLayout);
        viewpanelLayout.setHorizontalGroup(
            viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        viewpanelLayout.setVerticalGroup(
            viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        home.add(viewpanel, "card7");

        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 1060, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        // TODO add your handling code here:
        home.removeAll();
        home.repaint();
        home.revalidate();
        
        home.add(addpanel);
        home.repaint();
        home.revalidate();
        refresh1();
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton3ActionPerformed
        // TODO add your handling code here:
         home.removeAll();
        home.repaint();
        home.revalidate();
        
        home.add(homepanel);
        home.repaint();
        home.revalidate();
    }//GEN-LAST:event_rSButton3ActionPerformed

    private void rSButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton2MouseClicked

    }//GEN-LAST:event_rSButton2MouseClicked

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
       String sql="insert into book values(?,?,?,?,?,?,?,?,?)";
        try{
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1,jtext1.getText());
            pst.setString(2,jtext2.getText());
            pst.setString(3,(String) jComboBox2.getSelectedItem());
            pst.setString(4,jtext3.getText());
            pst.setString(5,jtext4.getText());
            pst.setString(6,jtext5.getText());
            pst.setString(7,jtext6.getText());
            pst.setString(8,jtext7.getText());
            pst.setBytes(9, book_image);
            pst.execute();
            JOptionPane.showMessageDialog(null,"New Book Appended");
            refresh1();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_add_buttonActionPerformed

    private void jtext5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext5ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jLabel10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseDragged
        // TODO add your handling code here:
         int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-mouseX ,y-mouseY);
    }//GEN-LAST:event_jLabel10MouseDragged

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
           mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_jLabel10MousePressed

    private void jtext13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext13ActionPerformed
public void update(){
     try{
            String sql="select * from book";
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            rs=(OracleResultSet) pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
}
    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed
        // TODO add your handling code here:
         int p=JOptionPane.showConfirmDialog(null,"Are You Sure","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql="delete from book where book_id=?";
            try{
                pst=(OraclePreparedStatement) conn.prepareStatement(sql);
                pst.setString(1,jtext8.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Deleted");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }update();
        refresh2();
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void rSButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton5ActionPerformed
        // TODO add your handling code here:
         home.removeAll();
        home.repaint();
        home.revalidate();
        
        home.add(deletepanel);
        home.repaint();
        home.revalidate();
        refresh2();
        try{
            String sql="select * from book";
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            rs=(OracleResultSet) pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_rSButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row=jTable2.getSelectedRow();
        String Table_click=(jTable2.getModel().getValueAt(row,0).toString());
        try{
            TableModel model=jTable2.getModel();
            String sql="select * from book where book_id='"+Table_click+"'";
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            rs=(OracleResultSet) pst.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("book_id");
                jtext8.setText(add1);
                String add2=rs.getString("book_title");
                jtext9.setText(add2);
                String cat1=model.getValueAt(row, 2).toString();
                switch(cat1){
                    case "B.Com":
                        jComboBox1.setSelectedIndex(0);
                        break;
                    case "M.Com":
                        jComboBox1.setSelectedIndex(1);
                        break;
                    case "B.Sc":
                        jComboBox1.setSelectedIndex(2);
                        break;
                    case "BCA":
                        jComboBox1.setSelectedIndex(3);
                        break;
                    case "MCA":
                        jComboBox1.setSelectedIndex(4);
                        break;
                    case "MBA":
                        jComboBox1.setSelectedIndex(5);
                        break;
                    case "Engineering":
                        jComboBox1.setSelectedIndex(6);
                        break;
                    case "Comic":
                        jComboBox1.setSelectedIndex(7);
                        break;
                    case "Historical":
                        jComboBox1.setSelectedIndex(8);
                        break;
                    case "Novels":
                        jComboBox1.setSelectedIndex(9);
                        break;
                }
                String add4=rs.getString("author_name");
                jtext10.setText(add4);
                String add5=rs.getString("publication");
                jtext11.setText(add5);
                String add6=rs.getString("edition");
                jtext12.setText(add6);
                String add7=rs.getString("pages");
                jtext13.setText(add7);
                String add8=rs.getString("price");
                jtext14.setText(add7);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jtext14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext14ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
     public void search()
    {
        try{
            String sql="select * from book";
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            rs=(OracleResultSet) pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        try{
         String selection=(String)jComboBox3.getSelectedItem();
         String sql="select * from book where "+selection+"=?";
         pst=(OraclePreparedStatement) conn.prepareStatement(sql);
         pst.setString(1,jTextField1.getText());
         rs=(OracleResultSet) pst.executeQuery();
         jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jTextField1KeyReleased
    public void update1()
    {
        try{
            String sql="select * from book";
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            rs=(OracleResultSet) pst.executeQuery();
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void rSButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton6ActionPerformed
        // TODO add your handling code here:
         home.removeAll();
        home.repaint();
        home.revalidate();
        
        home.add(updatepanel);
        home.repaint();
        home.revalidate();
        update1();
    }//GEN-LAST:event_rSButton6ActionPerformed

    private void jtext20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext20ActionPerformed
private void refresh3()
{
    jtext15.setText(null);
    jtext16.setText(null);
    jComboBox4.setSelectedIndex(0);
    jtext17.setText(null);
    jtext18.setText(null);
    jtext19.setText(null);
    jtext20.setText(null);
    jtext21.setText(null);
}

    private void rSButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton8ActionPerformed
        // TODO add your handling code here:
        try{
           String val1=jtext15.getText();
           String val2=jtext16.getText();
           String val3;
           val3 = (String) jComboBox4.getSelectedItem();
           String val4=jtext17.getText();
           String val5=jtext18.getText();
           String val6=jtext19.getText();
           String val7=jtext20.getText();
           String val8=jtext21.getText();
           
           String sql="update book set book_title='"+val2+"',category='"+val3+"',author_name='"+val4+"',publication='"+val5+"',edition='"+val6+"',pages='"+val7+"',price='"+val8+"' where book_id='"+val1+"'";
           pst=(OraclePreparedStatement) conn.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(null,"Book Details Modified"); 
           refresh3();
           update1();
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e); 
        }
    }//GEN-LAST:event_rSButton8ActionPerformed

    private void jtext21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext21ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
       
        int row=jTable4.getSelectedRow();
        String Table_click=(jTable4.getModel().getValueAt(row,0).toString());
        try{
            TableModel model=jTable4.getModel();
            String sql="select * from book where book_id='"+Table_click+"'";
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            rs=(OracleResultSet) pst.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("book_id");
                jtext15.setText(add1);
                String add2=rs.getString("book_title");
                jtext16.setText(add2);
                String cat1=model.getValueAt(row, 2).toString();
                switch(cat1){
                    case "B.Com":
                        jComboBox4.setSelectedIndex(0);
                        break;
                    case "M.Com":
                        jComboBox4.setSelectedIndex(1);
                        break;
                    case "B.Sc":
                        jComboBox4.setSelectedIndex(2);
                        break;
                    case "BCA":
                        jComboBox4.setSelectedIndex(3);
                        break;
                    case "MCA":
                        jComboBox4.setSelectedIndex(4);
                        break;
                    case "MBA":
                        jComboBox4.setSelectedIndex(5);
                        break;
                    case "Engineering":
                        jComboBox4.setSelectedIndex(6);
                        break;
                    case "Comic":
                        jComboBox4.setSelectedIndex(7);
                        break;
                    case "Historical":
                        jComboBox4.setSelectedIndex(8);
                        break;
                    case "Novels":
                        jComboBox4.setSelectedIndex(9);
                        break;
                }
                String add4=rs.getString("author_name");
                jtext17.setText(add4);
                String add5=rs.getString("publication");
                jtext18.setText(add5);
                String add6=rs.getString("edition");
                jtext19.setText(add6);
                String add7=rs.getString("pages");
                jtext20.setText(add7);
                String add8=rs.getString("price");
                jtext21.setText(add7);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jTable4MouseClicked

    private void rSButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton9ActionPerformed

    private void rSButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton7ActionPerformed
        // TODO add your handling code here:
        home.removeAll();
        home.repaint();
        home.revalidate();

        home.add(searchpanel);
        home.repaint();
        home.revalidate();
        search();
    }//GEN-LAST:event_rSButton7ActionPerformed
    public void view()
    {
        try{
            String sql="select * from register";
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            rs=(OracleResultSet) pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void rSButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton4ActionPerformed
        // TODO add your handling code here:
         home.removeAll();
        home.repaint();
        home.revalidate();

        home.add(viewpanel);
        home.repaint();
        home.revalidate();
        view();
    }//GEN-LAST:event_rSButton4ActionPerformed

    private void rSButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton10ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Main m=new Main();
        m.setVisible(true);
    }//GEN-LAST:event_rSButton10ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void rSButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton11ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        try{
            File Image=new File(filename);
            FileInputStream fis=new FileInputStream(Image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf, 0, readNum);
            }
            book_image=bos.toByteArray();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_rSButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton add_button;
    private javax.swing.JPanel addpanel;
    private javax.swing.JLabel date;
    private javax.swing.JPanel deletepanel;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel image;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    public javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtext1;
    private javax.swing.JTextField jtext10;
    private javax.swing.JTextField jtext11;
    private javax.swing.JTextField jtext12;
    private javax.swing.JTextField jtext13;
    private javax.swing.JTextField jtext14;
    private javax.swing.JTextField jtext15;
    private javax.swing.JTextField jtext16;
    private javax.swing.JTextField jtext17;
    private javax.swing.JTextField jtext18;
    private javax.swing.JTextField jtext19;
    private javax.swing.JTextField jtext2;
    private javax.swing.JTextField jtext20;
    private javax.swing.JTextField jtext21;
    private javax.swing.JTextField jtext3;
    private javax.swing.JTextField jtext4;
    private javax.swing.JTextField jtext5;
    private javax.swing.JTextField jtext6;
    private javax.swing.JTextField jtext7;
    private javax.swing.JTextField jtext8;
    private javax.swing.JTextField jtext9;
    private javax.swing.JPanel menupanel;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton10;
    private rojeru_san.RSButton rSButton11;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSButton rSButton4;
    private rojeru_san.RSButton rSButton5;
    private rojeru_san.RSButton rSButton6;
    private rojeru_san.RSButton rSButton7;
    private rojeru_san.RSButton rSButton8;
    private rojeru_san.RSButton rSButton9;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JPanel side_menu;
    private javax.swing.JLabel time;
    private javax.swing.JPanel updatepanel;
    private javax.swing.JPanel viewpanel;
    // End of variables declaration//GEN-END:variables
String filename=null;
byte[] book_image=null;
private ImageIcon format=null;
}
